content_generator:
  llm_model: "gemini-1.5-pro-latest"
  meta_llm_model: "gemini-1.5-pro-latest"
  max_output_tokens: 8192
  prompt_template: "souzatharsis/podcastfy_multimodal_cleanmarkup"
  prompt_commit: "b2365f11"
  longform_prompt_template: "souzatharsis/podcastfy_longform"
  longform_prompt_commit: "acfdbc91" #"ff865019"
  cleaner_prompt_template: "souzatharsis/podcastfy_longform_clean"
  cleaner_prompt_commit: "8c110a0b"
  rewriter_prompt_template: "souzatharsis/podcast_rewriter"
  rewriter_prompt_commit: "8ee296fb"
content_extractor:
  youtube_url_patterns:
    - "youtube.com"
    - "youtu.be"

website_extractor:
  jina_api_url: "https://r.jina.ai"
  markdown_cleaning:
    remove_patterns:
      - '!\[.*?\]\(.*?\)'
      - '\[([^\]]+)\]\([^\)]+\)'
      - 'https?://\S+|www\.\S+'

youtube_transcriber:
  remove_phrases:
    - "[music]"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"


website_extractor:
  markdown_cleaning:
    remove_patterns:
      - '\[.*?\]'  # Remove square brackets and their contents
      - '\(.*?\)'  # Remove parentheses and their contents
      - '^\s*[-*]\s'  # Remove list item markers
      - '^\s*\d+\.\s'  # Remove numbered list markers
      - '^\s*#+'  # Remove markdown headers
  unwanted_tags:
    - 'script'
    - 'style'
    - 'nav'
    - 'footer'
    - 'header'
    - 'aside'
    - 'noscript'
  user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
  timeout: 10  # Request timeout in seconds
